### ISSUE TITLE
Cropping transparent PNG files results in black background

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWire#1006]
Tried on a couple of different servers and a few different image and it seems to be a consistent problem. Let me know if you need an example image to test.

**Comment by phlppschrr** [comment]
Sounds familiar. I guess this pull request should fix it:
https://github.com/ryancramerdesign/ProcessWire/pull/846

**Comment by adrianbj** [comment]
Thanks for that - the changes in that PR work great for me.

Ryan - can you see any reason not to incorporate these ASAP?

**Comment by adrianbj** [comment]
On a related note, it might be nice to have a Photoshop-style gray/white checkerboard displayed behind images so you can see which ones are transparent rather than with a white background.

**Comment by adrianbj** [comment]
Thanks for the fix @ryancramerdesign and @phlppschrr.

I am still keen on the idea of the checkerboard background, but I'll close this issue since the real problem is now fixed!

**Comment by lesaff** [comment]
I am using PW 3.0.39 and still experiencing this issue. It doesn't happen all the time though. Approx. one every 6 transparent PNG files will get black background when used with `size()` function. See example below:

![screen shot 2016-11-14 at 10 13 29 am](https://cloud.githubusercontent.com/assets/1151181/20267872/09e7b91a-aa53-11e6-883d-5fcadff38edb.png)

EDIT: Black background appears only when PNG file(s) were preprocessed with ImageOptim (stripped off metadata, color profiles and gamma info).

**Comment by horst-n** [comment]
ImageOptim is a **POST**processor, **not** a **PRE**processor!
It is totally useless to manipulate an image again, after compressed it through ImageOptim!
