### ISSUE TITLE
redirectLoginURL does not work with multi-language URLs

### ISSUE THREAD

**Issue by landitus** [ryancramerdesign/ProcessWire#1400]
I think this is bug or maybe it needs to be documented. In a multi-lingual site, when setting the redirect login URL option in the template like this: /login/?ref={id}, the GET variable is discarded. When the custom login template gets loaded, the appropriate language is sorted out automatically but with no variables. So the resulting URL is "http://site/login" without the GET variable. Should this be sorted out automatically by PW? Is there a special tag for the language? Does this work with multi-language?

**Comment by LostKobrakai** [comment]
Just prevent the redirect by not hardcoding the url, but using something like this: `$pages->get("/login/")->url` which will get you the localized url of the page.

**Comment by landitus** [comment]
I've tried it and it's not working. The $pages->get("/login/")->url gets appended as a is, as the php is not parsed as a URL, but a as string. It looks like the redirect URL field for templates only accepts text and parses only the id when entered as a tag {id}.

**Comment by LostKobrakai** [comment]
Ah sorry, missed the part that you're using the template setting for the redirect.

**Comment by ryancramerdesign** [comment]
What's occurring here is a double redirect. First the redirect to your login page (issued by ProcessPageView), which includes the ref={id}, and second is the redirect issued by LanguageSupportPageNames, which does not include the query string. As a security policy, LanguageSupportPageNames does not pass along query strings when it performs redirects, since a query string from user input is an unknown that can potentially contain anything. 

What I'd suggest as a solution is to provide the ID to your login page, rather than the URL. That way it should be able to render your login page without a redirect, while maintaining the original page URL in the browser. Upon login success, you can simply redirect to the current URL, and it should be on the correct page, i.e. 
```````
$session->redirect('./');
```````

**Comment by ryancramerdesign** [comment]
…and yes I agree this needs more documentation. If you find the suggest solution works for your case, please let me know and I'll update the description/notes for this field to clarify this option.

**Comment by landitus** [comment]
I tried using the id for the login page (in my case is 1039), but when I save the template, the value is not saved. Actually, the field kind of disappears. 

<img width="970" alt="screen shot 2015-09-21 at 10 18 53" src="https://cloud.githubusercontent.com/assets/239215/9992769/7c4260fe-604a-11e5-821a-ee2d534996e4.png">
<img width="973" alt="screen shot 2015-09-21 at 10 20 18" src="https://cloud.githubusercontent.com/assets/239215/9992771/81457f50-604a-11e5-893d-5606531deba8.png">

**Comment by ryancramerdesign** [comment]
You are right, sorry about that. I've just pushed a fix. Please let me know how it works out for you.

**Comment by landitus** [comment]
thanks Ryan. The redirect now works with and page ID, but I'm still not sure how to achieve a redirect with the ID of the previous requested page, like ?ref={id}

**Comment by ryancramerdesign** [comment]
Sorry, I meant to follow-up with he rest of the solution. You can retrieve the page that was was requested before the login page by accessing: 
`````
$pageID = $session->getFor('ProcessPageView', 'loginRequestPageID'); 
if($pageID) {
  $yourPage = $pages->get($pageID); 
}
`````

**Comment by LostKobrakai** [comment]
@ryancramerdesign That last part is even new to me. If that's not the case already this should really be documented somewhere.

**Comment by ryancramerdesign** [comment]
It should be new to you (and me) as it was literally added yesterday. :)
